# https://esphome.io/components/sensor/ld2410.html

substitutions:
  mmwave_sensorname: "mmwave"  #lowercase only!
  mmwave_friendly_sensorname: "mmWave" #unused, because names would get way too long

uart:
  - id: uart_0
    rx_pin: "${uart_0_rx_pin}"
    tx_pin: "${uart_0_tx_pin}"
    baud_rate: 256000
    parity: NONE
    stop_bits: 1
  - id: uart_1
    rx_pin: "${uart_1_rx_pin}"
    tx_pin: "${uart_1_tx_pin}"
    baud_rate: 256000
    parity: NONE
    stop_bits: 1
  - id: uart_2
    rx_pin: "${uart_2_rx_pin}"
    tx_pin: "${uart_2_tx_pin}"
    baud_rate: 256000
    parity: NONE
    stop_bits: 1

ld2410:
  - id: "${mmwave_sensorname}_${occupancy_zone_name_0}"
    uart_id: uart_0
    throttle: 1500ms
  - id: "${mmwave_sensorname}_${occupancy_zone_name_1}"
    uart_id: uart_1
    throttle: 1500ms
  - id: "${mmwave_sensorname}_${occupancy_zone_name_2}"
    uart_id: uart_2
    throttle: 1500ms

select:
  - platform: ld2410
    ld2410_id: "${mmwave_sensorname}_${occupancy_zone_name_0}"
    distance_resolution:
      name: "${occupancy_zone_friendlyname_0} distance resolution"
    baud_rate:
      name: "${occupancy_zone_friendlyname_0} baud rate"
    light_function:
      name: "${occupancy_zone_friendlyname_0} light function"
    out_pin_level:
      name: "${occupancy_zone_friendlyname_0} out pin level"
  - platform: ld2410
    ld2410_id: "${mmwave_sensorname}_${occupancy_zone_name_1}"
    distance_resolution:
      name: "${occupancy_zone_friendlyname_1} distance resolution"
    baud_rate:
      name: "${occupancy_zone_friendlyname_1} baud rate"
    light_function:
      name: "${occupancy_zone_friendlyname_1} light function"
    out_pin_level:
      name: "${occupancy_zone_friendlyname_1} out pin level"
  - platform: ld2410
    ld2410_id: "${mmwave_sensorname}_${occupancy_zone_name_2}"
    distance_resolution:
      name: "${occupancy_zone_friendlyname_2} distance resolution"
    baud_rate:
      name: "${occupancy_zone_friendlyname_2} baud rate"
    light_function:
      name: "${occupancy_zone_friendlyname_2} light function"
    out_pin_level:
      name: "${occupancy_zone_friendlyname_2} out pin level"
      
binary_sensor:
  - platform: ld2410
    ld2410_id: "${mmwave_sensorname}_${occupancy_zone_name_0}"
    has_target:
      name: "${occupancy_zone_friendlyname_0} Radar Target"
      id: "${mmwave_sensorname}_${occupancy_zone_name_0}_radar_target"
    has_moving_target:
      name: "${occupancy_zone_friendlyname_0} Radar Moving Target"
    has_still_target:
      name: "${occupancy_zone_friendlyname_0} Radar Still Target"
    out_pin_presence_status:
      name: "${occupancy_zone_friendlyname_0} out pin presence status"
  - platform: ld2410
    ld2410_id: "${mmwave_sensorname}_${occupancy_zone_name_1}"
    has_target:
      name: "${occupancy_zone_friendlyname_1} Radar Target"
      id: "${mmwave_sensorname}_${occupancy_zone_name_1}_radar_target"
    has_moving_target:
      name: "${occupancy_zone_friendlyname_1} Radar Moving Target"
    has_still_target:
      name: "${occupancy_zone_friendlyname_1} Radar Still Target"
    out_pin_presence_status:
      name: "${occupancy_zone_friendlyname_1} out pin presence status"
  - platform: ld2410
    ld2410_id: "${mmwave_sensorname}_${occupancy_zone_name_2}"
    has_target:
      name: "${occupancy_zone_friendlyname_2} Radar Target"
      id: "${mmwave_sensorname}_${occupancy_zone_name_2}_radar_target"
    has_moving_target:
      name: "${occupancy_zone_friendlyname_2} Radar Moving Target"
    has_still_target:
      name: "${occupancy_zone_friendlyname_2} Radar Still Target"
    out_pin_presence_status:
      name: "${occupancy_zone_friendlyname_2} out pin presence status"

sensor:
  - platform: ld2410
    ld2410_id: "${mmwave_sensorname}_${occupancy_zone_name_0}"
    light:
      name: "${occupancy_zone_friendlyname_0} light"
    moving_distance:
      name : "${occupancy_zone_friendlyname_0} Moving Distance"
    still_distance:
      name: "${occupancy_zone_friendlyname_0} Still Distance"
    moving_energy:
      name: "${occupancy_zone_friendlyname_0} Move Energy"
    still_energy:
      name: "${occupancy_zone_friendlyname_0} Still Energy"
    detection_distance:
      name: "${occupancy_zone_friendlyname_0} Detection Distance"
    g0:
      move_energy:
        name: "${occupancy_zone_friendlyname_0} g0 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_0} g0 still energy"
    g1:
      move_energy:
        name: "${occupancy_zone_friendlyname_0} g1 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_0} g1 still energy"
    g2:
      move_energy:
        name: "${occupancy_zone_friendlyname_0} g2 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_0} g2 still energy"
    g3:
      move_energy:
        name: "${occupancy_zone_friendlyname_0} g3 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_0} g3 still energy"
    g4:
      move_energy:
        name: "${occupancy_zone_friendlyname_0} g4 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_0} g4 still energy"
    g5:
      move_energy:
        name: "${occupancy_zone_friendlyname_0} g5 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_0} g5 still energy"
    g6:
      move_energy:
        name: "${occupancy_zone_friendlyname_0} g6 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_0} g6 still energy"
    g7:
      move_energy:
        name: "${occupancy_zone_friendlyname_0} g7 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_0} g7 still energy"
    g8:
      move_energy:
        name: "${occupancy_zone_friendlyname_0} g8 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_0} g8 still energy"
  - platform: ld2410
    ld2410_id: "${mmwave_sensorname}_${occupancy_zone_name_1}"
    light:
      name: "${occupancy_zone_friendlyname_1} light"
    moving_distance:
      name : "${occupancy_zone_friendlyname_1} Moving Distance"
    still_distance:
      name: "${occupancy_zone_friendlyname_1} Still Distance"
    moving_energy:
      name: "${occupancy_zone_friendlyname_1} Move Energy"
    still_energy:
      name: "${occupancy_zone_friendlyname_1} Still Energy"
    detection_distance:
      name: "${occupancy_zone_friendlyname_1} Detection Distance"
    g0:
      move_energy:
        name: "${occupancy_zone_friendlyname_1} g0 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_1} g0 still energy"
    g1:
      move_energy:
        name: "${occupancy_zone_friendlyname_1} g1 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_1} g1 still energy"
    g2:
      move_energy:
        name: "${occupancy_zone_friendlyname_1} g2 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_1} g2 still energy"
    g3:
      move_energy:
        name: "${occupancy_zone_friendlyname_1} g3 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_1} g3 still energy"
    g4:
      move_energy:
        name: "${occupancy_zone_friendlyname_1} g4 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_1} g4 still energy"
    g5:
      move_energy:
        name: "${occupancy_zone_friendlyname_1} g5 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_1} g5 still energy"
    g6:
      move_energy:
        name: "${occupancy_zone_friendlyname_1} g6 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_1} g6 still energy"
    g7:
      move_energy:
        name: "${occupancy_zone_friendlyname_1} g7 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_1} g7 still energy"
    g8:
      move_energy:
        name: "${occupancy_zone_friendlyname_1} g8 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_1} g8 still energy"
  - platform: ld2410
    ld2410_id: "${mmwave_sensorname}_${occupancy_zone_name_2}"
    light:
      name: "${occupancy_zone_friendlyname_2} light"
    moving_distance:
      name : "${occupancy_zone_friendlyname_2} Moving Distance"
    still_distance:
      name: "${occupancy_zone_friendlyname_2} Still Distance"
    moving_energy:
      name: "${occupancy_zone_friendlyname_2} Move Energy"
    still_energy:
      name: "${occupancy_zone_friendlyname_2} Still Energy"
    detection_distance:
      name: "${occupancy_zone_friendlyname_2} Detection Distance"
    g0:
      move_energy:
        name: "${occupancy_zone_friendlyname_2} g0 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_2} g0 still energy"
    g1:
      move_energy:
        name: "${occupancy_zone_friendlyname_2} g1 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_2} g1 still energy"
    g2:
      move_energy:
        name: "${occupancy_zone_friendlyname_2} g2 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_2} g2 still energy"
    g3:
      move_energy:
        name: "${occupancy_zone_friendlyname_2} g3 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_2} g3 still energy"
    g4:
      move_energy:
        name: "${occupancy_zone_friendlyname_2} g4 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_2} g4 still energy"
    g5:
      move_energy:
        name: "${occupancy_zone_friendlyname_2} g5 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_2} g5 still energy"
    g6:
      move_energy:
        name: "${occupancy_zone_friendlyname_2} g6 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_2} g6 still energy"
    g7:
      move_energy:
        name: "${occupancy_zone_friendlyname_2} g7 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_2} g7 still energy"
    g8:
      move_energy:
        name: "${occupancy_zone_friendlyname_2} g8 move energy"
      still_energy:
        name: "${occupancy_zone_friendlyname_2} g8 still energy"

switch:
  - platform: ld2410
    ld2410_id: "${mmwave_sensorname}_${occupancy_zone_name_0}"
    engineering_mode:
      name: "${occupancy_zone_friendlyname_0} engineering mode"
    bluetooth:
      name: "${occupancy_zone_friendlyname_0} control bluetooth"
  - platform: ld2410
    ld2410_id: "${mmwave_sensorname}_${occupancy_zone_name_1}"
    engineering_mode:
      name: "${occupancy_zone_friendlyname_1} engineering mode"
    bluetooth:
      name: "${occupancy_zone_friendlyname_1} control bluetooth"
  - platform: ld2410
    ld2410_id: "${mmwave_sensorname}_${occupancy_zone_name_2}"
    engineering_mode:
      name: "${occupancy_zone_friendlyname_2} engineering mode"
    bluetooth:
      name: "${occupancy_zone_friendlyname_2} control bluetooth"

number:
  - platform: ld2410
    ld2410_id: "${mmwave_sensorname}_${occupancy_zone_name_0}"
    timeout:
      name: "${occupancy_zone_friendlyname_0} timeout"
    light_threshold:
      name: "${occupancy_zone_friendlyname_0} light threshold"
    max_move_distance_gate:
      name: "${occupancy_zone_friendlyname_0} max move distance gate"
    max_still_distance_gate:
      name: "${occupancy_zone_friendlyname_0} max still distance gate"
    g0:
      move_threshold:
        name: "${occupancy_zone_friendlyname_0} g0 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_0} g0 still threshold"
    g1:
      move_threshold:
        name: "${occupancy_zone_friendlyname_0} g1 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_0} g1 still threshold"
    g2:
      move_threshold:
        name: "${occupancy_zone_friendlyname_0} g2 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_0} g2 still threshold"
    g3:
      move_threshold:
        name: "${occupancy_zone_friendlyname_0} g3 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_0} g3 still threshold"
    g4:
      move_threshold:
        name: "${occupancy_zone_friendlyname_0} g4 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_0} g4 still threshold"
    g5:
      move_threshold:
        name: "${occupancy_zone_friendlyname_0} g5 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_0} g5 still threshold"
    g6:
      move_threshold:
        name: "${occupancy_zone_friendlyname_0} g6 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_0} g6 still threshold"
    g7:
      move_threshold:
        name: "${occupancy_zone_friendlyname_0} g7 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_0} g7 still threshold"
    g8:
      move_threshold:
        name: "${occupancy_zone_friendlyname_0} g8 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_0} g8 still threshold"
  - platform: ld2410
    ld2410_id: "${mmwave_sensorname}_${occupancy_zone_name_1}"
    timeout:
      name: "${occupancy_zone_friendlyname_1} timeout"
    light_threshold:
      name: "${occupancy_zone_friendlyname_1} light threshold"
    max_move_distance_gate:
      name: "${occupancy_zone_friendlyname_1} max move distance gate"
    max_still_distance_gate:
      name: "${occupancy_zone_friendlyname_1} max still distance gate"
    g0:
      move_threshold:
        name: "${occupancy_zone_friendlyname_1} g0 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_1} g0 still threshold"
    g1:
      move_threshold:
        name: "${occupancy_zone_friendlyname_1} g1 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_1} g1 still threshold"
    g2:
      move_threshold:
        name: "${occupancy_zone_friendlyname_1} g2 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_1} g2 still threshold"
    g3:
      move_threshold:
        name: "${occupancy_zone_friendlyname_1} g3 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_1} g3 still threshold"
    g4:
      move_threshold:
        name: "${occupancy_zone_friendlyname_1} g4 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_1} g4 still threshold"
    g5:
      move_threshold:
        name: "${occupancy_zone_friendlyname_1} g5 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_1} g5 still threshold"
    g6:
      move_threshold:
        name: "${occupancy_zone_friendlyname_1} g6 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_1} g6 still threshold"
    g7:
      move_threshold:
        name: "${occupancy_zone_friendlyname_1} g7 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_1} g7 still threshold"
    g8:
      move_threshold:
        name: "${occupancy_zone_friendlyname_1} g8 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_1} g8 still threshold"
  - platform: ld2410
    ld2410_id: "${mmwave_sensorname}_${occupancy_zone_name_2}"
    timeout:
      name: "${occupancy_zone_friendlyname_2} timeout"
    light_threshold:
      name: "${occupancy_zone_friendlyname_2} light threshold"
    max_move_distance_gate:
      name: "${occupancy_zone_friendlyname_2} max move distance gate"
    max_still_distance_gate:
      name: "${occupancy_zone_friendlyname_2} max still distance gate"
    g0:
      move_threshold:
        name: "${occupancy_zone_friendlyname_2} g0 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_2} g0 still threshold"
    g1:
      move_threshold:
        name: "${occupancy_zone_friendlyname_2} g1 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_2} g1 still threshold"
    g2:
      move_threshold:
        name: "${occupancy_zone_friendlyname_2} g2 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_2} g2 still threshold"
    g3:
      move_threshold:
        name: "${occupancy_zone_friendlyname_2} g3 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_2} g3 still threshold"
    g4:
      move_threshold:
        name: "${occupancy_zone_friendlyname_2} g4 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_2} g4 still threshold"
    g5:
      move_threshold:
        name: "${occupancy_zone_friendlyname_2} g5 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_2} g5 still threshold"
    g6:
      move_threshold:
        name: "${occupancy_zone_friendlyname_2} g6 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_2} g6 still threshold"
    g7:
      move_threshold:
        name: "${occupancy_zone_friendlyname_2} g7 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_2} g7 still threshold"
    g8:
      move_threshold:
        name: "${occupancy_zone_friendlyname_2} g8 move threshold"
      still_threshold:
        name: "${occupancy_zone_friendlyname_2} g8 still threshold"

button:
  - platform: ld2410
    ld2410_id: "${mmwave_sensorname}_${occupancy_zone_name_0}"
    factory_reset:
      entity_category: diagnostic
      name: "${occupancy_zone_friendlyname_0} factory reset"
    restart:
      entity_category: diagnostic
      name: "${occupancy_zone_friendlyname_0} restart"
    query_params:
      entity_category: diagnostic
      name: "${occupancy_zone_friendlyname_0} query params"
  - platform: ld2410
    ld2410_id: "${mmwave_sensorname}_${occupancy_zone_name_1}"
    factory_reset:
      entity_category: diagnostic
      name: "${occupancy_zone_friendlyname_1} factory reset"
    restart:
      entity_category: diagnostic
      name: "${occupancy_zone_friendlyname_1} restart"
    query_params:
      entity_category: diagnostic
      name: "${occupancy_zone_friendlyname_1} query params"
  - platform: ld2410
    ld2410_id: "${mmwave_sensorname}_${occupancy_zone_name_2}"
    factory_reset:
      entity_category: diagnostic
      name: "${occupancy_zone_friendlyname_2} factory reset"
    restart:
      entity_category: diagnostic
      name: "${occupancy_zone_friendlyname_2} restart"
    query_params:
      entity_category: diagnostic
      name: "${occupancy_zone_friendlyname_2} query params"

text_sensor:
  - platform: ld2410
    ld2410_id: "${mmwave_sensorname}_${occupancy_zone_name_0}"
    version:
      name: "${occupancy_zone_friendlyname_0} firmware version"
    mac_address:
      name: "${occupancy_zone_friendlyname_0} ble mac address"
  - platform: ld2410
    ld2410_id: "${mmwave_sensorname}_${occupancy_zone_name_1}"
    version:
      name: "${occupancy_zone_friendlyname_1} firmware version"
    mac_address:
      name: "${occupancy_zone_friendlyname_1} ble mac address"
  - platform: ld2410
    ld2410_id: "${mmwave_sensorname}_${occupancy_zone_name_2}"
    version:
      name: "${occupancy_zone_friendlyname_2} firmware version"
    mac_address:
      name: "${occupancy_zone_friendlyname_2} ble mac address"