  # https://esphome.io/components/sensor/duty_cycle
sensor:
  - platform: duty_cycle
    pin: "${fsr_0_pin}"
    name: "${bed_occupancy_zone_friendlyname_0}"
    id: "${bed_occupancy_zone_name_0}"
    update_interval: 1s

  - platform: duty_cycle
    pin: "${fsr_1_pin}"
    name: "${bed_occupancy_zone_friendlyname_1}"
    id: "${bed_occupancy_zone_name_1}"
    update_interval: 1s

  - platform: duty_cycle
    pin: "${fsr_2_pin}"
    name: "${bed_occupancy_zone_friendlyname_2}"
    id: "${bed_occupancy_zone_name_2}"
    update_interval: 1s

  - platform: duty_cycle
    pin: "${fsr_3_pin}"
    name: "${bed_occupancy_zone_friendlyname_3}"
    id: "${bed_occupancy_zone_name_3}"
    update_interval: 1s

  - platform: duty_cycle
    pin: "${fsr_4_pin}"
    name: "${bed_occupancy_zone_friendlyname_4}"
    id: "${bed_occupancy_zone_name_4}"
    update_interval: 1s

  - platform: duty_cycle
    pin: "${fsr_5_pin}"
    name: "${bed_occupancy_zone_friendlyname_5}"
    id: "${bed_occupancy_zone_name_5}"
    update_interval: 1s

binary_sensor:
  - platform: template
    name: "${bed_occupancy_zone_friendlyname_0} Occupied"
    id: "${bed_occupancy_zone_name_0}_occupied"
    lambda: |-
      if (id(${bed_occupancy_zone_name_0}_off_threshold_active).state == true){
        if (id(${bed_occupancy_zone_name_0}).state < id(${bed_occupancy_zone_name_0}_on_threshold).state) {
          // Bed set to occupied
          return true;
        } else if ((id(${bed_occupancy_zone_name_0}).state >= id(${bed_occupancy_zone_name_0}_on_threshold).state) & (id(${bed_occupancy_zone_name_0}).state < id(${bed_occupancy_zone_name_0}_off_threshold).state)){
          // Keep bed occupancy state as is if the duty cycle value is between "bed on" and "bed off" number values
          if (id(${bed_occupancy_zone_name_0}_occupied).state == true){
            return true;
          }
          else {
            return false;
          }
        } else if (id(${bed_occupancy_zone_name_0}).state >= id(${bed_occupancy_zone_name_0}_off_threshold).state){
          // Bed set to unoccupied
          return false;
        } else {
          // just in case if an unexpected state happens
          return false;
        }
      } else {
        if (id(${bed_occupancy_zone_name_0}).state < id(${bed_occupancy_zone_name_0}_on_threshold).state) {
          // Bed set to occupied
          return true;
        } else if (id(${bed_occupancy_zone_name_0}).state >= id(${bed_occupancy_zone_name_0}_on_threshold).state){
          // Bed set to unoccupied
          return false;
        } else {
          // just in case if an unexpected state happens
          return false;
        }
      }

  - platform: template
    name: "${bed_occupancy_zone_friendlyname_1} Occupied"
    id: "${bed_occupancy_zone_name_1}_occupied"
    lambda: |-
      if (id(${bed_occupancy_zone_name_1}_off_threshold_active).state == true){
        if (id(${bed_occupancy_zone_name_1}).state < id(${bed_occupancy_zone_name_1}_on_threshold).state) {
          // Bed set to occupied
          return true;
        } else if ((id(${bed_occupancy_zone_name_1}).state >= id(${bed_occupancy_zone_name_1}_on_threshold).state) & (id(${bed_occupancy_zone_name_1}).state < id(${bed_occupancy_zone_name_1}_off_threshold).state)){
          // Keep bed occupancy state as is if the duty cycle value is between "bed on" and "bed off" number values
          if (id(${bed_occupancy_zone_name_1}_occupied).state == true){
            return true;
          }
          else {
            return false;
          }
        } else if (id(${bed_occupancy_zone_name_1}).state >= id(${bed_occupancy_zone_name_1}_off_threshold).state){
          // Bed set to unoccupied
          return false;
        } else {
          // just in case if an unexpected state happens
          return false;
        }
      } else {
        if (id(${bed_occupancy_zone_name_1}).state < id(${bed_occupancy_zone_name_1}_on_threshold).state) {
          // Bed set to occupied
          return true;
        } else if (id(${bed_occupancy_zone_name_1}).state >= id(${bed_occupancy_zone_name_1}_on_threshold).state){
          // Bed set to unoccupied
          return false;
        } else {
          // just in case if an unexpected state happens
          return false;
        }
      }

  - platform: template
    name: "${bed_occupancy_zone_friendlyname_2} Occupied"
    id: "${bed_occupancy_zone_name_2}_occupied"
    lambda: |-
      if (id(${bed_occupancy_zone_name_2}_off_threshold_active).state == true){
        if (id(${bed_occupancy_zone_name_2}).state < id(${bed_occupancy_zone_name_2}_on_threshold).state) {
          // Bed set to occupied
          return true;
        } else if ((id(${bed_occupancy_zone_name_2}).state >= id(${bed_occupancy_zone_name_2}_on_threshold).state) & (id(${bed_occupancy_zone_name_2}).state < id(${bed_occupancy_zone_name_2}_off_threshold).state)){
          // Keep bed occupancy state as is if the duty cycle value is between "bed on" and "bed off" number values
          if (id(${bed_occupancy_zone_name_2}_occupied).state == true){
            return true;
          }
          else {
            return false;
          }
        } else if (id(${bed_occupancy_zone_name_2}).state >= id(${bed_occupancy_zone_name_2}_off_threshold).state){
          // Bed set to unoccupied
          return false;
        } else {
          // just in case if an unexpected state happens
          return false;
        }
      } else {
        if (id(${bed_occupancy_zone_name_2}).state < id(${bed_occupancy_zone_name_2}_on_threshold).state) {
          // Bed set to occupied
          return true;
        } else if (id(${bed_occupancy_zone_name_2}).state >= id(${bed_occupancy_zone_name_2}_on_threshold).state){
          // Bed set to unoccupied
          return false;
        } else {
          // just in case if an unexpected state happens
          return false;
        }
      }

  - platform: template
    name: "${bed_occupancy_zone_friendlyname_3} Occupied"
    id: "${bed_occupancy_zone_name_3}_occupied"
    lambda: |-
      if (id(${bed_occupancy_zone_name_3}_off_threshold_active).state == true){
        if (id(${bed_occupancy_zone_name_3}).state < id(${bed_occupancy_zone_name_3}_on_threshold).state) {
          // Bed set to occupied
          return true;
        } else if ((id(${bed_occupancy_zone_name_3}).state >= id(${bed_occupancy_zone_name_3}_on_threshold).state) & (id(${bed_occupancy_zone_name_3}).state < id(${bed_occupancy_zone_name_3}_off_threshold).state)){
          // Keep bed occupancy state as is if the duty cycle value is between "bed on" and "bed off" number values
          if (id(${bed_occupancy_zone_name_3}_occupied).state == true){
            return true;
          }
          else {
            return false;
          }
        } else if (id(${bed_occupancy_zone_name_3}).state >= id(${bed_occupancy_zone_name_3}_off_threshold).state){
          // Bed set to unoccupied
          return false;
        } else {
          // just in case if an unexpected state happens
          return false;
        }
      } else {
        if (id(${bed_occupancy_zone_name_3}).state < id(${bed_occupancy_zone_name_3}_on_threshold).state) {
          // Bed set to occupied
          return true;
        } else if (id(${bed_occupancy_zone_name_3}).state >= id(${bed_occupancy_zone_name_3}_on_threshold).state){
          // Bed set to unoccupied
          return false;
        } else {
          // just in case if an unexpected state happens
          return false;
        }
      }

  - platform: template
    name: "${bed_occupancy_zone_friendlyname_4} Occupied"
    id: "${bed_occupancy_zone_name_4}_occupied"
    lambda: |-
      if (id(${bed_occupancy_zone_name_4}_off_threshold_active).state == true){
        if (id(${bed_occupancy_zone_name_4}).state < id(${bed_occupancy_zone_name_4}_on_threshold).state) {
          // Bed set to occupied
          return true;
        } else if ((id(${bed_occupancy_zone_name_4}).state >= id(${bed_occupancy_zone_name_4}_on_threshold).state) & (id(${bed_occupancy_zone_name_4}).state < id(${bed_occupancy_zone_name_4}_off_threshold).state)){
          // Keep bed occupancy state as is if the duty cycle value is between "bed on" and "bed off" number values
          if (id(${bed_occupancy_zone_name_4}_occupied).state == true){
            return true;
          }
          else {
            return false;
          }
        } else if (id(${bed_occupancy_zone_name_4}).state >= id(${bed_occupancy_zone_name_4}_off_threshold).state){
          // Bed set to unoccupied
          return false;
        } else {
          // just in case if an unexpected state happens
          return false;
        }
      } else {
        if (id(${bed_occupancy_zone_name_4}).state < id(${bed_occupancy_zone_name_4}_on_threshold).state) {
          // Bed set to occupied
          return true;
        } else if (id(${bed_occupancy_zone_name_4}).state >= id(${bed_occupancy_zone_name_4}_on_threshold).state){
          // Bed set to unoccupied
          return false;
        } else {
          // just in case if an unexpected state happens
          return false;
        }
      }

  - platform: template
    name: "${bed_occupancy_zone_friendlyname_5} Occupied"
    id: "${bed_occupancy_zone_name_5}_occupied"
    lambda: |-
      if (id(${bed_occupancy_zone_name_5}_off_threshold_active).state == true){
        if (id(${bed_occupancy_zone_name_5}).state < id(${bed_occupancy_zone_name_5}_on_threshold).state) {
          // Bed set to occupied
          return true;
        } else if ((id(${bed_occupancy_zone_name_5}).state >= id(${bed_occupancy_zone_name_5}_on_threshold).state) & (id(${bed_occupancy_zone_name_5}).state < id(${bed_occupancy_zone_name_5}_off_threshold).state)){
          // Keep bed occupancy state as is if the duty cycle value is between "bed on" and "bed off" number values
          if (id(${bed_occupancy_zone_name_5}_occupied).state == true){
            return true;
          }
          else {
            return false;
          }
        } else if (id(${bed_occupancy_zone_name_5}).state >= id(${bed_occupancy_zone_name_5}_off_threshold).state){
          // Bed set to unoccupied
          return false;
        } else {
          // just in case if an unexpected state happens
          return false;
        }
      } else {
        if (id(${bed_occupancy_zone_name_5}).state < id(${bed_occupancy_zone_name_5}_on_threshold).state) {
          // Bed set to occupied
          return true;
        } else if (id(${bed_occupancy_zone_name_5}).state >= id(${bed_occupancy_zone_name_5}_on_threshold).state){
          // Bed set to unoccupied
          return false;
        } else {
          // just in case if an unexpected state happens
          return false;
        }
      }

  - platform: template
    name: "${bed_occupancy_zone_friendlyname_0} Off-Level"
    id: "${bed_occupancy_zone_name_0}_off_threshold_active"
    lambda: |-
      if (id(${bed_occupancy_zone_name_0}_on_threshold).state < id(${bed_occupancy_zone_name_0}_off_threshold).state){
        return true;
      } else {
        return false;
      }

  - platform: template
    name: "${bed_occupancy_zone_friendlyname_1} Off-Level"
    id: "${bed_occupancy_zone_name_1}_off_threshold_active"
    lambda: |-
      if (id(${bed_occupancy_zone_name_1}_on_threshold).state < id(${bed_occupancy_zone_name_1}_off_threshold).state){
        return true;
      } else {
        return false;
      }

  - platform: template
    name: "${bed_occupancy_zone_friendlyname_2} Off-Level"
    id: "${bed_occupancy_zone_name_2}_off_threshold_active"
    lambda: |-
      if (id(${bed_occupancy_zone_name_2}_on_threshold).state < id(${bed_occupancy_zone_name_2}_off_threshold).state){
        return true;
      } else {
        return false;
      }

  - platform: template
    name: "${bed_occupancy_zone_friendlyname_3} Off-Level"
    id: "${bed_occupancy_zone_name_3}_off_threshold_active"
    lambda: |-
      if (id(${bed_occupancy_zone_name_3}_on_threshold).state < id(${bed_occupancy_zone_name_3}_off_threshold).state){
        return true;
      } else {
        return false;
      }

  - platform: template
    name: "${bed_occupancy_zone_friendlyname_4} Off-Level"
    id: "${bed_occupancy_zone_name_4}_off_threshold_active"
    lambda: |-
      if (id(${bed_occupancy_zone_name_4}_on_threshold).state < id(${bed_occupancy_zone_name_4}_off_threshold).state){
        return true;
      } else {
        return false;
      }

  - platform: template
    name: "${bed_occupancy_zone_friendlyname_5} Off-Level"
    id: "${bed_occupancy_zone_name_5}_off_threshold_active"
    lambda: |-
      if (id(${bed_occupancy_zone_name_5}_on_threshold).state < id(${bed_occupancy_zone_name_5}_off_threshold).state){
        return true;
      } else {
        return false;
      }

number:
  - platform: template
    name: "${bed_occupancy_zone_friendlyname_0} ON-Level"
    id: "${bed_occupancy_zone_name_0}_on_threshold"
    optimistic: true
    min_value: 0
    max_value: 100
    initial_value: 50
    restore_value: true
    step: 1

  - platform: template
    name: "${bed_occupancy_zone_friendlyname_0} OFF-Level"
    id: "${bed_occupancy_zone_name_0}_off_threshold"
    optimistic: true
    min_value: 0
    max_value: 100
    initial_value: 75
    restore_value: true
    step: 1

  - platform: template
    name: "${bed_occupancy_zone_friendlyname_1} ON-Level"
    id: "${bed_occupancy_zone_name_1}_on_threshold"
    optimistic: true
    min_value: 0
    max_value: 100
    initial_value: 50
    restore_value: true
    step: 1

  - platform: template
    name: "${bed_occupancy_zone_friendlyname_1} OFF-Level"
    id: "${bed_occupancy_zone_name_1}_off_threshold"
    optimistic: true
    min_value: 0
    max_value: 100
    initial_value: 75
    restore_value: true
    step: 1

  - platform: template
    name: "${bed_occupancy_zone_friendlyname_2} ON-Level"
    id: "${bed_occupancy_zone_name_2}_on_threshold"
    optimistic: true
    min_value: 0
    max_value: 100
    initial_value: 50
    restore_value: true
    step: 1

  - platform: template
    name: "${bed_occupancy_zone_friendlyname_2} OFF-Level"
    id: "${bed_occupancy_zone_name_2}_off_threshold"
    optimistic: true
    min_value: 0
    max_value: 100
    initial_value: 75
    restore_value: true
    step: 1

  - platform: template
    name: "${bed_occupancy_zone_friendlyname_3} ON-Level"
    id: "${bed_occupancy_zone_name_3}_on_threshold"
    optimistic: true
    min_value: 0
    max_value: 100
    initial_value: 50
    restore_value: true
    step: 1

  - platform: template
    name: "${bed_occupancy_zone_friendlyname_3} OFF-Level"
    id: "${bed_occupancy_zone_name_3}_off_threshold"
    optimistic: true
    min_value: 0
    max_value: 100
    initial_value: 75
    restore_value: true
    step: 1

  - platform: template
    name: "${bed_occupancy_zone_friendlyname_4} ON-Level"
    id: "${bed_occupancy_zone_name_4}_on_threshold"
    optimistic: true
    min_value: 0
    max_value: 100
    initial_value: 50
    restore_value: true
    step: 1

  - platform: template
    name: "${bed_occupancy_zone_friendlyname_4} OFF-Level"
    id: "${bed_occupancy_zone_name_4}_off_threshold"
    optimistic: true
    min_value: 0
    max_value: 100
    initial_value: 75
    restore_value: true
    step: 1

  - platform: template
    name: "${bed_occupancy_zone_friendlyname_5} ON-Level"
    id: "${bed_occupancy_zone_name_5}_on_threshold"
    optimistic: true
    min_value: 0
    max_value: 100
    initial_value: 50
    restore_value: true
    step: 1

  - platform: template
    name: "${bed_occupancy_zone_friendlyname_5} OFF-Level"
    id: "${bed_occupancy_zone_name_5}_off_threshold"
    optimistic: true
    min_value: 0
    max_value: 100
    initial_value: 75
    restore_value: true
    step: 1