# ESP32-Wr00m-32 (NOT ESP32-D2WD!)
# platformio: https://docs.platformio.org/en/latest/boards/espressif32/nodemcu-32s.html#nodemcu-32s
# board data: https://www.az-delivery.de/products/esp32-developmentboard?_pos=5&_sid=ee2dc30a4&_ss=r

# Free GPIO's
#  GPIO 23
#  GPIO 19
#  GPIO 18
#  GPIO 00
#  GPIO 02
#  GPIO 15
#  GPIO 13

substitutions:
  # pins for FSR resistance strips
  fsr_0_pin: GPIO34
  fsr_1_pin: GPIO35
  fsr_2_pin: GPIO32
  fsr_3_pin: GPIO33
  fsr_4_pin: GPIO25
  fsr_5_pin: GPIO26
  # GPIO pins for PIR sensor HIGH/LOW Input
  pir_0_pin: GPIO27
  pir_1_pin: GPIO14
  pir_2_pin: GPIO12
  # uart pins for mmWave sensors:
  uart_0_rx_pin: GPIO01
  uart_0_tx_pin: GPIO03
  uart_1_rx_pin: GPIO04
  uart_1_tx_pin: GPIO05
  uart_2_rx_pin: GPIO16
  uart_2_tx_pin: GPIO17

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

i2c:
  sda: GPIO21
  scl: GPIO22
  id: bus_a